engines:
  rubocop:
    enabled: false
  golint:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: true
  pep8:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python
      - javascript
ratings:
  paths:
  - "**.py"
exclude_paths:
- static/admin/js/vendor/**/*
- "*/migrations/*.py"