language: python
python:
  - "3.4"
  - "3.5"
before_install:
  - sudo apt-get update
  - sudo apt-get install socat
install:
  - pip install -r requirements_dev.txt
  - pip install -r requirements.txt
script:
  - python --version
  - python manage.py timevortex --validate --settings=timevortex.settings.local
after_success: coveralls