# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timevortex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
