# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 00:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timevortex', '0003_variables'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sites',
            new_name='Site',
        ),
        migrations.RenameModel(
            old_name='Variables',
            new_name='Variable',
        ),
    ]
