# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timevortex', '0004_auto_20151229_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_type',
            field=models.CharField(
                blank=True,
                choices=[(None, 'Pas de type particulier'), ('METEAR', 'METEAR')],
                default=None,
                max_length=2,
                null=True),
        ),
    ]
