# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timevortex', '0005_auto_20151229_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_type',
            field=models.CharField(blank=True, choices=[('0', 'Pas de type particulier'), ('1', 'METEAR')], max_length=2, null=True),
        ),
    ]
