# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-23 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timevortex', '0006_auto_20151229_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_type',
            field=models.CharField(
                blank=True,
                choices=[('0', 'Pas de type particulier'), ('1', 'METEAR'), ('2', 'HOME_TYPE')],
                max_length=2,
                null=True),
        ),
    ]
