# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-23 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timevortex', '0009_auto_20160923_1555'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
