# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StubsAPIOpening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_metear_api', models.BooleanField(default=False)),
            ],
        ),
    ]
