# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-04 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timevortex', '0009_auto_20160923_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentCostSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tty_port', models.CharField(blank=True, max_length=200, null=True)),
                ('timeout', models.PositiveSmallIntegerField()),
                ('usb_retry', models.PositiveSmallIntegerField()),
                ('ch1_kwh_variable', models.ForeignKey(blank=True, null=True,
                                                       on_delete=django.db.models.deletion.SET_NULL,
                                                       related_name='ch1_kwh_variable', to='timevortex.Variable')),
                ('ch1_variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                   related_name='ch1_variable', to='timevortex.Variable')),
                ('ch2_kwh_variable', models.ForeignKey(blank=True, null=True,
                                                       on_delete=django.db.models.deletion.SET_NULL,
                                                       related_name='ch2_kwh_variable', to='timevortex.Variable')),
                ('ch2_variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                   related_name='ch2_variable', to='timevortex.Variable')),
                ('ch3_kwh_variable', models.ForeignKey(blank=True, null=True,
                                                       on_delete=django.db.models.deletion.SET_NULL,
                                                       related_name='ch3_kwh_variable', to='timevortex.Variable')),
                ('ch3_variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                   related_name='ch3_variable', to='timevortex.Variable')),
                ('currentcost_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                           to='timevortex.Variable')),
                ('tmpr_variable', models.ForeignKey(blank=True, null=True,
                                                    on_delete=django.db.models.deletion.SET_NULL,
                                                    related_name='tmpr_variable', to='timevortex.Variable')),
            ],
        ),
    ]
